# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 40))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BarraHerramientas = QtWidgets.QFrame(self.centralwidget)
        self.BarraHerramientas.setMinimumSize(QtCore.QSize(0, 40))
        self.BarraHerramientas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BarraHerramientas.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.BarraHerramientas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BarraHerramientas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BarraHerramientas.setObjectName("BarraHerramientas")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BarraHerramientas)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMenu = QtWidgets.QPushButton(self.BarraHerramientas)
        self.btnMenu.setMinimumSize(QtCore.QSize(200, 35))
        self.btnMenu.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btnMenu.setStyleSheet("QPushButton\n"
"{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:2px solid #949494;\n"
"background-color: #ff0000;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imajenes e iconos/barra-de-menus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_2.addWidget(self.btnMenu)
        spacerItem = QtWidgets.QSpacerItem(383, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnMinimisar = QtWidgets.QPushButton(self.BarraHerramientas)
        self.btnMinimisar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btnMinimisar.setStyleSheet("QPushButton\n"
"{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:5px solid #949494;\n"
"background-color: #ff0000;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.btnMinimisar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imajenes e iconos/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimisar.setIcon(icon1)
        self.btnMinimisar.setIconSize(QtCore.QSize(32, 32))
        self.btnMinimisar.setObjectName("btnMinimisar")
        self.horizontalLayout_2.addWidget(self.btnMinimisar)
        self.btnRestaurar = QtWidgets.QPushButton(self.BarraHerramientas)
        self.btnRestaurar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btnRestaurar.setStyleSheet("QPushButton\n"
"{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:5px solid #949494;\n"
"background-color: #ff0000;\n"
"}\n"
"\n"
"\n"
"")
        self.btnRestaurar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Imajenes e iconos/restaurar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRestaurar.setIcon(icon2)
        self.btnRestaurar.setIconSize(QtCore.QSize(32, 32))
        self.btnRestaurar.setObjectName("btnRestaurar")
        self.horizontalLayout_2.addWidget(self.btnRestaurar)
        self.btnMaximisar = QtWidgets.QPushButton(self.BarraHerramientas)
        self.btnMaximisar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btnMaximisar.setStyleSheet("QPushButton\n"
"{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:5px solid #949494;\n"
"background-color: #ff0000;\n"
"}\n"
"\n"
"\n"
"")
        self.btnMaximisar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Imajenes e iconos/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMaximisar.setIcon(icon3)
        self.btnMaximisar.setIconSize(QtCore.QSize(32, 32))
        self.btnMaximisar.setObjectName("btnMaximisar")
        self.horizontalLayout_2.addWidget(self.btnMaximisar)
        self.btnCerrar = QtWidgets.QPushButton(self.BarraHerramientas)
        self.btnCerrar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btnCerrar.setStyleSheet("QPushButton\n"
"{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border:5px solid #949494;\n"
"background-color: #ff0000;\n"
"}\n"
"\n"
"\n"
"")
        self.btnCerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Imajenes e iconos/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCerrar.setIcon(icon4)
        self.btnCerrar.setIconSize(QtCore.QSize(32, 32))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout_2.addWidget(self.btnCerrar)
        self.verticalLayout.addWidget(self.BarraHerramientas)
        self.windows = QtWidgets.QFrame(self.centralwidget)
        self.windows.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.windows.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.windows.setLineWidth(0)
        self.windows.setObjectName("windows")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.windows)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu = QtWidgets.QFrame(self.windows)
        self.Menu.setMinimumSize(QtCore.QSize(200, 0))
        self.Menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.Menu.setStyleSheet("QFrame{\n"
"background-color: rgb(159, 159, 159);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(159, 159, 159);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius:20px}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius:20px\n"
"}")
        self.Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu.setObjectName("Menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Inicio = QtWidgets.QPushButton(self.Menu)
        self.Inicio.setMinimumSize(QtCore.QSize(0, 40))
        self.Inicio.setMaximumSize(QtCore.QSize(16777215, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Imajenes e iconos/pagina-de-inicio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Inicio.setIcon(icon5)
        self.Inicio.setIconSize(QtCore.QSize(32, 32))
        self.Inicio.setObjectName("Inicio")
        self.verticalLayout_3.addWidget(self.Inicio)
        self.Software = QtWidgets.QPushButton(self.Menu)
        self.Software.setMinimumSize(QtCore.QSize(0, 40))
        self.Software.setMaximumSize(QtCore.QSize(16777215, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Imajenes e iconos/lenguaje-de-codificacion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Software.setIcon(icon6)
        self.Software.setIconSize(QtCore.QSize(32, 32))
        self.Software.setObjectName("Software")
        self.verticalLayout_3.addWidget(self.Software)
        self.Diseno = QtWidgets.QPushButton(self.Menu)
        self.Diseno.setMinimumSize(QtCore.QSize(0, 40))
        self.Diseno.setMaximumSize(QtCore.QSize(16777215, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Imajenes e iconos/diseno-grafico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Diseno.setIcon(icon7)
        self.Diseno.setIconSize(QtCore.QSize(32, 32))
        self.Diseno.setObjectName("Diseno")
        self.verticalLayout_3.addWidget(self.Diseno)
        self.Office = QtWidgets.QPushButton(self.Menu)
        self.Office.setMinimumSize(QtCore.QSize(0, 40))
        self.Office.setMaximumSize(QtCore.QSize(16777215, 40))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Imajenes e iconos/office.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Office.setIcon(icon8)
        self.Office.setIconSize(QtCore.QSize(32, 32))
        self.Office.setObjectName("Office")
        self.verticalLayout_3.addWidget(self.Office)
        self.Seguridad = QtWidgets.QPushButton(self.Menu)
        self.Seguridad.setMinimumSize(QtCore.QSize(0, 40))
        self.Seguridad.setMaximumSize(QtCore.QSize(16777215, 40))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Imajenes e iconos/seguridad-informatica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Seguridad.setIcon(icon9)
        self.Seguridad.setIconSize(QtCore.QSize(32, 32))
        self.Seguridad.setObjectName("Seguridad")
        self.verticalLayout_3.addWidget(self.Seguridad)
        spacerItem1 = QtWidgets.QSpacerItem(20, 262, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.Asistente = QtWidgets.QPushButton(self.Menu)
        self.Asistente.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Imajenes e iconos/realidad-virtual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Asistente.setIcon(icon10)
        self.Asistente.setIconSize(QtCore.QSize(50, 50))
        self.Asistente.setObjectName("Asistente")
        self.verticalLayout_3.addWidget(self.Asistente)
        self.horizontalLayout.addWidget(self.Menu)
        self.pague = QtWidgets.QFrame(self.windows)
        self.pague.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pague.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pague.setObjectName("pague")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pague)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Masterpague = QtWidgets.QStackedWidget(self.pague)
        self.Masterpague.setObjectName("Masterpague")
        self.PgInicio = QtWidgets.QWidget()
        self.PgInicio.setObjectName("PgInicio")
        self.pushButton = QtWidgets.QPushButton(self.PgInicio)
        self.pushButton.setGeometry(QtCore.QRect(120, 140, 291, 121))
        self.pushButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.Masterpague.addWidget(self.PgInicio)
        self.PgSoftware = QtWidgets.QWidget()
        self.PgSoftware.setObjectName("PgSoftware")
        self.pushButton_2 = QtWidgets.QPushButton(self.PgSoftware)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 150, 261, 151))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Masterpague.addWidget(self.PgSoftware)
        self.PgDiseno = QtWidgets.QWidget()
        self.PgDiseno.setObjectName("PgDiseno")
        self.pushButton_3 = QtWidgets.QPushButton(self.PgDiseno)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 130, 311, 221))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.Masterpague.addWidget(self.PgDiseno)
        self.PgOffice = QtWidgets.QWidget()
        self.PgOffice.setObjectName("PgOffice")
        self.pushButton_4 = QtWidgets.QPushButton(self.PgOffice)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 150, 291, 211))
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.Masterpague.addWidget(self.PgOffice)
        self.PgSeguridad = QtWidgets.QWidget()
        self.PgSeguridad.setObjectName("PgSeguridad")
        self.pushButton_5 = QtWidgets.QPushButton(self.PgSeguridad)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 140, 341, 211))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.Masterpague.addWidget(self.PgSeguridad)
        self.PgJuego = QtWidgets.QWidget()
        self.PgJuego.setObjectName("PgJuego")
        self.pushButton_11 = QtWidgets.QPushButton(self.PgJuego)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 120, 361, 251))
        self.pushButton_11.setStyleSheet("background-color: rgb(64, 131, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.Masterpague.addWidget(self.PgJuego)
        self.verticalLayout_2.addWidget(self.Masterpague)
        self.horizontalLayout.addWidget(self.pague)
        self.verticalLayout.addWidget(self.windows)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Masterpague.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMenu.setText(_translate("MainWindow", "  Menu"))
        self.Inicio.setText(_translate("MainWindow", "Inicio"))
        self.Software.setText(_translate("MainWindow", "Software"))
        self.Diseno.setText(_translate("MainWindow", "Diseño"))
        self.Office.setText(_translate("MainWindow", "Office"))
        self.Seguridad.setText(_translate("MainWindow", "Seguridad"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
